// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARxuWgmAcVMuHI2pRmUdBFy9anXcdVKWI',
    appId: '1:59364518993:web:1c35633659058936fc5c70',
    messagingSenderId: '59364518993',
    projectId: 'ubhan-drive',
    authDomain: 'ubhan-drive.firebaseapp.com',
    databaseURL: 'https://ubhan-drive-default-rtdb.firebaseio.com',
    storageBucket: 'ubhan-drive.appspot.com',
    measurementId: 'G-BXH3GXT4ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF13v4mXSH4Qy8pJL2EcvBoREcyWgKzG4',
    appId: '1:59364518993:android:d078295adc544460fc5c70',
    messagingSenderId: '59364518993',
    projectId: 'ubhan-drive',
    databaseURL: 'https://ubhan-drive-default-rtdb.firebaseio.com',
    storageBucket: 'ubhan-drive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVjfD7fWwtnbubLBr5F9jInFKEHKblPuc',
    appId: '1:59364518993:ios:334d4c148615c845fc5c70',
    messagingSenderId: '59364518993',
    projectId: 'ubhan-drive',
    databaseURL: 'https://ubhan-drive-default-rtdb.firebaseio.com',
    storageBucket: 'ubhan-drive.appspot.com',
    androidClientId: '59364518993-q6l7jbfhrng2ajjsban8s5prtgk9dto6.apps.googleusercontent.com',
    iosClientId: '59364518993-1bobcgnn9j7n17aggdd2dfk86rdvv61t.apps.googleusercontent.com',
    iosBundleId: 'com.example.driveUbhan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVjfD7fWwtnbubLBr5F9jInFKEHKblPuc',
    appId: '1:59364518993:ios:22a5425e03531170fc5c70',
    messagingSenderId: '59364518993',
    projectId: 'ubhan-drive',
    databaseURL: 'https://ubhan-drive-default-rtdb.firebaseio.com',
    storageBucket: 'ubhan-drive.appspot.com',
    androidClientId: '59364518993-q6l7jbfhrng2ajjsban8s5prtgk9dto6.apps.googleusercontent.com',
    iosClientId: '59364518993-hdtorl5d8iit0trtkjqst3hjdmntu1a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.driveUbhan.RunnerTests',
  );
}
